apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app
  labels:
    app: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: blog-app
          # image: registry.registry.svc.cluster.local:5000/blog-app:latest
          image: 10.106.5.196:5000/blog-app:aac13a41100d4040650fdc09134d4fe06a092e30
          ports:
            - containerPort: 5000
